name: Deploy Docs Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: gh-pages

env:
  ZIG_VERSION: 0.13.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Build docs
        run: zig build docs --summary all

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          folder: zig-out/docs



